### ISSUE TITLE
Tone.set() and other methods are undocumented

### ISSUE THREAD

**Issue by ericandrewlewis** [Tonejs/tonejs.github.io#10]
`Tone.set()` seems like a useful method to expose in the documentation, since it's the way to update a value like attack on an envelope, etc.

However I don't see it in [the Tone documentation](https://tonejs.github.io/docs/r12/Tone) or classes that inherit from it.

**Comment by tambien** [comment]
Thanks for the issue. Originally i left these out to just try to simplify things a little because i wanted to surface just the most relevant info for each class, but the [latest version of the docs](https://tonejs.github.io/docs/14.3.40/Gain#set) includes get and set for all the classes that implement it.
